notebookserver:
  image: ipython/scipyserver
  ports:
    - 8888:8888
    - 8443:8888
  environment:
    - PASSWORD=
    - IPYTHONDIR=/userdata
  volumes:
   - notebooks:/notebooks
   - server/media:/notebooks/media
   - server/static:/notebooks/static
  # - ./userdata:/userdata
  # - reveal.js:/notebooks/reveal.js
  # - notebook_profile:/root/.ipython/profile_default
  # - notebook_profile:/userdata/profile_techfest
  # - notebook_profile:/root/.ipython/arsenn
