notebookserver:
  image: ipython/scipyserver
  ports:
    - 8888:8888
    - 8443:8888
  environment:
    - PASSWORD=
    - IPYTHONDIR=/userdata
  volumes:
   - notebooks:/notebooks
   - intro/media:/notebooks/media
   - intro/static:/notebooks/static
   - intro/reveal.js:/notebooks/reveal.js
